run:
    -fuser -k 8080/tcp
    uv run python -m trouble_shooter.main

unit:
    uv run pytest tests/unit --durations=10 -q

integration:
    uv run pytest tests/integration --durations=10 -q

test: unit integration

types:
    uv run pyrefly check --remove-unused-ignores

lint:
    uv run ruff check . --fix

format:
    uv run ruff format .

ci: format lint types test
