run:
    -fuser -k 8080/tcp
    uv run python main.py

test:
    uv run pytest tests --durations=10 -q

types:
    uv run pyrefly check --remove-unused-ignores

lint:
    uv run ruff check . --fix

format:
    uv run ruff format .

ci: format lint types test
