/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Validates one line of an .oidtrace.jsonl.gz file. Authoritative prose spec: docs/trace-format.md. Unknown extra fields are permitted everywhere (readers must ignore them); open enums (violations, event.kind, end_reason, vtype) are deliberately unconstrained strings.
 */
export type OIDTraceRecordFormatVersion1 = Header | SystemInfo | Exchange | Event | Summary;
export type Oid = string;
/**
 * Seconds since walk start, monotonic clock, microsecond precision
 */
export type Reltime = number;

export interface Header {
  type: 'header';
  format_version: 1;
  tool: string;
  /**
   * ISO 8601 UTC; the only wall-clock time in the file
   */
  started_at: string;
  label?: string;
  session: {
    /**
     * Random UUID per walk invocation; shared by all files of a matrix run
     */
    id: string;
    run: number;
    runs_total: number;
    [k: string]: unknown;
  };
  snmp: {
    version: '1' | '2c';
    [k: string]: unknown;
  };
  settings: {
    /**
     * 0 means plain GetNext walk
     */
    bulk_size: number;
    timeout_s: number;
    retries: number;
    start_oid: Oid;
    time_budget_s?: number;
    /**
     * Walk cursor continued from a previous run; start_oid remains the subtree bound
     */
    resume_from?: string;
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
export interface SystemInfo {
  type: 'system_info';
  at: Reltime;
  point: 'start' | 'end';
  values: {
    [k: string]: string | number;
  };
  [k: string]: unknown;
}
export interface Exchange {
  type: 'exchange';
  seq: number;
  request: {
    pdu: 'get' | 'getnext' | 'getbulk';
    request_id: number;
    /**
     * @minItems 1
     */
    oids: [Oid, ...Oid[]];
    non_repeaters?: number;
    max_repetitions?: number;
    [k: string]: unknown;
  };
  /**
   * @minItems 1
   */
  attempts: [
    {
      sent_at: Reltime;
      received_at: Reltime | null;
      /**
       * Open enum; socket-level error instead of silence. Known: icmp-port-unreachable, icmp-host-unreachable, send-failed. When set, received_at is null.
       */
      error?: string;
      [k: string]: unknown;
    },
    ...{
      sent_at: Reltime;
      received_at: Reltime | null;
      /**
       * Open enum; socket-level error instead of silence. Known: icmp-port-unreachable, icmp-host-unreachable, send-failed. When set, received_at is null.
       */
      error?: string;
      [k: string]: unknown;
    }[],
  ];
  response?: {
    /**
     * As returned by the device; compare with request.request_id
     */
    request_id: number;
    error_status: number;
    error_index: number;
    varbinds: Varbind[];
    [k: string]: unknown;
  };
  stray_responses?: {
    received_at: Reltime;
    [k: string]: unknown;
  }[];
  violations?: string[];
  malformed?: {
    error: string;
    /**
     * Datagram size in bytes (the bytes themselves are not stored)
     */
    length?: number;
    salvaged?: {
      [k: string]: unknown;
    };
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
export interface Varbind {
  oid: Oid;
  /**
   * Known: Integer, OctetString, Null, ObjectIdentifier, IpAddress, Counter32, Gauge32, TimeTicks, Opaque, Counter64, NoSuchObject, NoSuchInstance, EndOfMibView; unknown BER tags as tag:0xNN
   */
  vtype: string;
  vlen: number;
  [k: string]: unknown;
}
export interface Event {
  type: 'event';
  at: Reltime;
  /**
   * Open enum; known: oid-loop-detected, walk-aborted-by-user, time-budget-exceeded
   */
  kind: string;
  detail?: {
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
export interface Summary {
  type: 'summary';
  at: Reltime;
  exchanges: number;
  oids_seen: number;
  /**
   * Open enum; known: completed, unresponsive, interrupted, time-budget-exceeded, oid-loop
   */
  end_reason: string;
  violation_counts: {
    [k: string]: number;
  };
  [k: string]: unknown;
}
