# generated by datamodel-codegen:
#   filename:  trace-format.schema.json

from __future__ import annotations
from pydantic import AwareDatetime, BaseModel, Field, RootModel, constr
from enum import Enum
from typing import Any, Literal


class Oid(RootModel[str]):
    root: str = Field(..., pattern="^[0-9]+(\\.[0-9]+)*$")


class Reltime(RootModel[float]):
    root: float = Field(
        ..., description="Seconds since walk start, monotonic clock, microsecond precision", ge=0.0
    )


class Varbind(BaseModel):
    oid: Oid
    vtype: str = Field(
        ...,
        description="Known: Integer, OctetString, Null, ObjectIdentifier, IpAddress, Counter32, Gauge32, TimeTicks, Opaque, Counter64, NoSuchObject, NoSuchInstance, EndOfMibView; unknown BER tags as tag:0xNN",
    )
    vlen: int = Field(..., ge=0)


class Session(BaseModel):
    id: str = Field(
        ..., description="Random UUID per walk invocation; shared by all files of a matrix run"
    )
    run: int = Field(..., ge=1)
    runs_total: int = Field(..., ge=1)


class Version(Enum):
    field_1 = "1"
    field_2c = "2c"


class Snmp(BaseModel):
    version: Version


class Settings(BaseModel):
    bulk_size: int = Field(..., description="0 means plain GetNext walk", ge=0)
    timeout_s: float = Field(..., gt=0.0)
    retries: int = Field(..., ge=0)
    start_oid: Oid
    time_budget_s: float | None = Field(default=None, gt=0.0)
    resume_from: Oid | None = Field(
        default=None,
        description="Walk cursor continued from a previous run; start_oid remains the subtree bound",
    )


class Header(BaseModel):
    type: Literal["header"]
    format_version: Literal[1]
    tool: str
    started_at: AwareDatetime = Field(
        ..., description="ISO 8601 UTC; the only wall-clock time in the file"
    )
    label: str | None = None
    session: Session
    snmp: Snmp
    settings: Settings


class Point(Enum):
    start = "start"
    end = "end"


class SystemInfo(BaseModel):
    type: Literal["system_info"]
    at: Reltime
    point: Point
    values: dict[constr(pattern=r"^[0-9]+(\.[0-9]+)*$"), str | int]


class Pdu(Enum):
    get = "get"
    getnext = "getnext"
    getbulk = "getbulk"


class Request(BaseModel):
    pdu: Pdu
    request_id: int
    oids: list[Oid] = Field(..., min_length=1)
    non_repeaters: int | None = Field(default=None, ge=0)
    max_repetitions: int | None = Field(default=None, ge=0)


class Attempt(BaseModel):
    sent_at: Reltime
    received_at: Reltime | None
    error: str | None = Field(
        default=None,
        description="Open enum; socket-level error instead of silence. Known: icmp-port-unreachable, icmp-host-unreachable, send-failed. When set, received_at is null.",
    )


class Response(BaseModel):
    request_id: int = Field(
        ..., description="As returned by the device; compare with request.request_id"
    )
    error_status: int
    error_index: int
    varbinds: list[Varbind]


class StrayResponse(BaseModel):
    received_at: Reltime


class Malformed(BaseModel):
    error: str
    length: int | None = Field(
        default=None,
        description="Datagram size in bytes (the bytes themselves are not stored)",
        ge=0,
    )
    salvaged: dict[str, Any] | None = None


class Exchange(BaseModel):
    type: Literal["exchange"]
    seq: int = Field(..., ge=1)
    request: Request
    attempts: list[Attempt] = Field(..., min_length=1)
    response: Response | None = None
    stray_responses: list[StrayResponse] | None = None
    violations: list[str] | None = None
    malformed: Malformed | None = None


class Event(BaseModel):
    type: Literal["event"]
    at: Reltime
    kind: str = Field(
        ...,
        description="Open enum; known: oid-loop-detected, walk-aborted-by-user, time-budget-exceeded",
    )
    detail: dict[str, Any] | None = None


class Summary(BaseModel):
    type: Literal["summary"]
    at: Reltime
    exchanges: int = Field(..., ge=0)
    oids_seen: int = Field(..., ge=0)
    end_reason: str = Field(
        ...,
        description="Open enum; known: completed, unresponsive, interrupted, time-budget-exceeded, oid-loop",
    )
    violation_counts: dict[str, int]


class OidtraceRecordFormatVersion1(RootModel[Header | SystemInfo | Exchange | Event | Summary]):
    root: Header | SystemInfo | Exchange | Event | Summary = Field(
        ...,
        description="Validates one line of an .oidtrace.jsonl.gz file. Authoritative prose spec: docs/trace-format.md. Unknown extra fields are permitted everywhere (readers must ignore them); open enums (violations, event.kind, end_reason, vtype) are deliberately unconstrained strings.",
        title="OIDTrace record (format version 1)",
    )
